"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExampleSwapToPrice__factory = exports.ExampleSlidingWindowOracle__factory = exports.ExampleOracleSimple__factory = exports.ExampleFlashSwap__factory = exports.ExampleComputeLiquidityValue__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ExampleComputeLiquidityValue__factory_1 = require("./ExampleComputeLiquidityValue__factory");
Object.defineProperty(exports, "ExampleComputeLiquidityValue__factory", { enumerable: true, get: function () { return ExampleComputeLiquidityValue__factory_1.ExampleComputeLiquidityValue__factory; } });
var ExampleFlashSwap__factory_1 = require("./ExampleFlashSwap__factory");
Object.defineProperty(exports, "ExampleFlashSwap__factory", { enumerable: true, get: function () { return ExampleFlashSwap__factory_1.ExampleFlashSwap__factory; } });
var ExampleOracleSimple__factory_1 = require("./ExampleOracleSimple__factory");
Object.defineProperty(exports, "ExampleOracleSimple__factory", { enumerable: true, get: function () { return ExampleOracleSimple__factory_1.ExampleOracleSimple__factory; } });
var ExampleSlidingWindowOracle__factory_1 = require("./ExampleSlidingWindowOracle__factory");
Object.defineProperty(exports, "ExampleSlidingWindowOracle__factory", { enumerable: true, get: function () { return ExampleSlidingWindowOracle__factory_1.ExampleSlidingWindowOracle__factory; } });
var ExampleSwapToPrice__factory_1 = require("./ExampleSwapToPrice__factory");
Object.defineProperty(exports, "ExampleSwapToPrice__factory", { enumerable: true, get: function () { return ExampleSwapToPrice__factory_1.ExampleSwapToPrice__factory; } });
