/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testContractSol from "./TestContract.sol";
export type { testContractSol };
import type * as uniswapV2 from "./uniswap-v2";
export type { uniswapV2 };
export type { HelloWorld } from "./HelloWorld";
export type { Multicall } from "./Multicall";
