"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IUniswapV2Pair__factory = exports.IUniswapV2Factory__factory = exports.IUniswapV2ERC20__factory = exports.IUniswapV2Callee__factory = exports.IERC20__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IERC20__factory_1 = require("./IERC20__factory");
Object.defineProperty(exports, "IERC20__factory", { enumerable: true, get: function () { return IERC20__factory_1.IERC20__factory; } });
var IUniswapV2Callee__factory_1 = require("./IUniswapV2Callee__factory");
Object.defineProperty(exports, "IUniswapV2Callee__factory", { enumerable: true, get: function () { return IUniswapV2Callee__factory_1.IUniswapV2Callee__factory; } });
var IUniswapV2ERC20__factory_1 = require("./IUniswapV2ERC20__factory");
Object.defineProperty(exports, "IUniswapV2ERC20__factory", { enumerable: true, get: function () { return IUniswapV2ERC20__factory_1.IUniswapV2ERC20__factory; } });
var IUniswapV2Factory__factory_1 = require("./IUniswapV2Factory__factory");
Object.defineProperty(exports, "IUniswapV2Factory__factory", { enumerable: true, get: function () { return IUniswapV2Factory__factory_1.IUniswapV2Factory__factory; } });
var IUniswapV2Pair__factory_1 = require("./IUniswapV2Pair__factory");
Object.defineProperty(exports, "IUniswapV2Pair__factory", { enumerable: true, get: function () { return IUniswapV2Pair__factory_1.IUniswapV2Pair__factory; } });
